name:"Java Build Action"

description : "compile and run java program"

runs:
 using:"composite"

 steps:
  -name:Compile Java
  run:javac Main.java
  shell:bash 
  
  -name:Run Java 
  run: java Main 
  shell:bash
